### ISSUE TITLE
The setting that makes `ngspice` not take forever to load model files

### ISSUE THREAD

**Issue by dan-fritchman** [dan-fritchman/Hdl21#104]
Ngspice, for whatever reason, has two modes of reading model files: 

(a) Eagerly, i.e. parsing everything upfront, or 
(b) On-demand, i.e. only what is needed by the circuit under test

For whatever reason: 
(1) They have choice (a) 
(2) It's a user-level setting to choose between choices (a) and (b), and 
(3) The default is the bad one, (a)

With the sky130 models choice (a) gets pretty slow, like dozens of seconds to invoke even an empty-netlist simulation. And since we have a test or two which can invoke the sky130/ `ngspice` combo now, this becomes important, at least to keeping the test time under, like, tens of seconds. There have been handfuls of threads, issues, and the like on the topic in SkyWater-world. 

The issue here: 

* Figure out how to set setting (b) 
* Figure out where to stick that setting
* At least have it written down one more place (here)

**Comment by ThomasPluck** [comment]
Strange idea, but, what if HDL21 either at install/import or with an explicit command opened ngspice as an interactive daemon using server mode, and HDL21 programs became its clients?

This way, the PDK modules can run lib/include commands for specific components when imported providing a one-time upfront cost to running HDL21 Sims.

This would be particularly useful for parameter sweeps or just prevent general bloating of library loading, which I think takes up practically all of Sim time at the moment.

In the install scenario - we would also need a small extra HDL21 management daemon that would free up the server if there hasn't been any client interaction for a while or rejects commands to repeat library loading etc.
