### ISSUE TITLE
Sky130 Digital Cells

### ISSUE THREAD

**Issue by ThomasPluck** [dan-fritchman/Hdl21#119]
@joamatab If the Sky130 GDSFactory PDK is going to use HDL21 to netlist, these will have to be added for everything to work as intended.

**Comment by joamatab** [comment]
yes Thomas

**Comment by ThomasPluck** [comment]
Digital cells are now added, should probably test these, but since they are just subcircuits - I can't imagine that they will do anything to strange in this current form
