### ISSUE TITLE
gdsfactory/hdl21 naming dispute

### ISSUE THREAD

**Issue by ThomasPluck** [dan-fritchman/Hdl21#120]
Both gdsfactory's Sky130 PDK and HDL21's PDK module are called "sky130" according to the Python Package Manager. And gdsfactory's package is `sky130` on pypi whereas hdl21's is `sky130-hdl21`.

What's the best course of action here, as we move to integrate hdl21 into the gdsfactory PDK?

@joamatab
@dan-fritchman

**Comment by joamatab** [comment]
How about being consistent with pypi and renaming `sky130` to `sky130-hdl21` ?

Im also happy to rename the gdsfactory one if that does not works well

**Comment by dan-fritchman** [comment]
FWIW the dashes make for invalid package names. 

```
>>> import something-dash-something-else
  File "<stdin>", line 1
    import something-dash-something-else
                    ^
SyntaxError: invalid syntax
```

Packages like [scikit-learn](https://pypi.org/project/scikit-learn/) adopt a similar shortening ("`import sklearn`").  

I don't really wanna run around changing it, much less all the other (mostly closed-source) PDK-packages which follow that same convention. But yeah, seems to be a problem; I don't think there's like a re-naming mechanism in `pyproject.toml` or `setup.py`, as some other languages support. (Is there?)

**Comment by ThomasPluck** [comment]
Do we have any idea what we wanna do here? Right now, I just have `sky130-hdl21` as `sky130_hdl21` in my package manager because just because it was easier for me to do.

**Comment by dan-fritchman** [comment]
I think naming these built-in PDKs `{name}hdl21` (no puncutation) or `{name}_hdl21` (underscore-separated) should work. 
And it's probably helpful to have the same "PyPi name" as "package name" (whatever they really call those two things).

**Comment by ThomasPluck** [comment]
I'm going to go with `sky130_hdl21`, simply because its easier on the eyes.

**Comment by ThomasPluck** [comment]
Added these to the current commit of #114, we are going with `{name}_hdl21`.
