### ISSUE TITLE
Add `pip install hdl21`, to the home page, right at the top

### ISSUE THREAD

**Issue by dan-fritchman** [dan-fritchman/Hdl21#136]
We often forget our chip brethren are used to some insane installation process where they need to download 30 things, edit 29 of them, `source` 500 environment variables, etc. Make it clear Hdl21 just requires `pip install`, and go.

**Comment by ThomasPluck** [comment]
To add to this, having rebuilt the open_pdks for the fifth (?) time on my local machine. I'd recommend that we point users to https://github.com/efabless/volare for minimal stress PDK installation.
