### ISSUE TITLE
Deprecate `setup.py`

### ISSUE THREAD

**Issue by ThomasPluck** [dan-fritchman/Hdl21#144]
As was pointed out in https://github.com/dan-fritchman/Hdl21/pull/114#discussion_r1233466318 calling `setup.py` directly from setuptools is deprecated:

https://setuptools.pypa.io/en/latest/deprecated/commands.html

Resolving this ticket would involve moving over all Hdl21 modules to using `pyproject.toml` as described in the documentation above.

**Comment by dan-fritchman** [comment]
Also #49

**Comment by dan-fritchman** [comment]
Gonna close as a duplicate, use #49.
