### ISSUE TITLE
Release v4

### ISSUE THREAD

**Issue by dan-fritchman** [dan-fritchman/Hdl21#150]
Plan: release version 4 this week or early next.  
Until then, planning to focus on: 

* (a) Any open bugs
* (b) Any "semi-bugs", i.e. common points of user confusion
* (c) Docs
* (d) Examples

To do: 

* Roll in pending PRs:
  * #114 
  * #148 
  * At least one to VLSIR, for the schema `literals`
* #152
  * #145 
  * #136 
  * #60 
  * Recent PDK additions
  * Lotta stuff about Bundles
* Also roll in: 
  * #139 
  * #140
  * #30
* Maybe roll in: 
  * #147 
  * #142
  * #120
  * #71  
  * #115 
* Examples:
  * #126 
  * #125 
* I think these are done(?): 
  * #68 
  * #39

**Comment by curtisma** [comment]
@dan-fritchman Can you close this?  v4 was released.
Maybe start a v5 release issue to start.  Or make a v4.1 or v5 milestone?

**Comment by dan-fritchman** [comment]
Didn't know we had so much housekeeping enthusiasm!  
A few reminders to future-selves as to what made it: 

* Partially in v4, remaining open to follow: 
  * #140 
  * #125 
* Didn't make it: 
  * #65 
  * #71 
  * #115 

Everything else in the list above is in v4.
