### ISSUE TITLE
Bring `pyproject.toml` Back!

### ISSUE THREAD

**Issue by dan-fritchman** [dan-fritchman/Hdl21#49]
@vighneshiyer pointed out (some time ago now) that `Poetry` now supports the feature we really wanted it to, when we ditched it: editable dev-mode installs. 

I think it's worth bringing back, when we have the chance.

**Comment by dan-fritchman** [comment]
I can also say firsthand, having used this on some other projects now, that Poetry does all the stuff we want for this project.  
Should be a relatively quick replacement of all the (4-5) `setup.py` files.

**Comment by dan-fritchman** [comment]
This should probably more accurately be titled:  
Bring `pyproject.toml` back!

Since nowadays one can run `pip install -e` on projects with a TOML config (and no setup.py), without needing Poetry.

**Comment by uduse** [comment]
I used poetry before and the editable dev install feature was the thing I wanted the most too :)))

**Comment by dan-fritchman** [comment]
One complication using the `pip`/ `pyproject.toml` combo: it doesn't appear to support the `dev-dependencies` feature.  
Tried this elsewhere to no luck, and found many issues around the internet to this effect:  
https://github.com/python-poetry/poetry/issues/3348

In `setup.py` the development-dependencies are an "extra feature", which just happens to be named `dev`. Tried that too, to no avail.

**Comment by dan-fritchman** [comment]
So two new notes here: 

* We at Hdl21 HQ are now playing with another project which relies on old-enough `pip` that at least *some* of our target `pyproject.toml` features won't work. And I think TOML just won't work period.  

* #149 started with a comment that "the setup.py method is now deprecated".  

It's not.  
The setuptools docs (linked in #149) say: 

> While it is perfectly fine that users write setup.py files to configure a package build (e.g. to specify binary extensions or customize commands), on recent versions of setuptools, running python setup.py directly as a script is considered deprecated. This also means that users should avoid running commands directly via python setup.py <command>.

So the deprecated thing is *running* `python setup.py <command>`.  
Which we don't do; in all cases invocation of that `setup` script (or at least advice on how to do so) comes though `pip`.
